In [1]:

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
data = pd.read_csv('/content/drive/MyDrive/Statistical Learning II/Project I/AQI and Lat Long of Countries complete.csv')
data.head()

Country              City  AQI Value AQI Category  CO AQI Value  \
0  Russian Federation        Praskoveya         51     Moderate             1   
1              Brazil  Presidente Dutra         41         Good             1   
2              Brazil  Presidente Dutra         41         Good             1   
3               Italy   Priolo Gargallo         66     Moderate             1   
4              Poland         Przasnysz         34         Good             1   

  CO AQI Category  Ozone AQI Value Ozone AQI Category  NO2 AQI Value  \
0            Good               36               Good              0   
1            Good                5               Good              1   
2            Good                5               Good              1   
3            Good               39               Good              2   
4            Good               34               Good              0   

  NO2 AQI Category  PM2.5 AQI Value PM2.5 AQI Category      lat      lng  SO2  
0             Good               51           Moderate  44.7444  44.2031    1  
1             Good               41               Good  -5.2900 -44.4900    1  
2             Good               41               Good -11.2958 -41.9869    0  
3             Good               66           Moderate  37.1667  15.1833    1  
4             Good               20               Good  53.0167  20.8833    1

In [4]:
data2 = pd.read_csv('/content/drive/MyDrive/Statistical Learning II/Project I/AQI and Lat Long of Countries.csv')
data2.head()

Country              City  AQI Value AQI Category  CO AQI Value  \
0  Russian Federation        Praskoveya         51     Moderate             1   
1              Brazil  Presidente Dutra         41         Good             1   
2              Brazil  Presidente Dutra         41         Good             1   
3               Italy   Priolo Gargallo         66     Moderate             1   
4              Poland         Przasnysz         34         Good             1   

  CO AQI Category  Ozone AQI Value Ozone AQI Category  NO2 AQI Value  \
0            Good               36               Good              0   
1            Good                5               Good              1   
2            Good                5               Good              1   
3            Good               39               Good              2   
4            Good               34               Good              0   

  NO2 AQI Category  PM2.5 AQI Value PM2.5 AQI Category      lat      lng  
0             Good               51           Moderate  44.7444  44.2031  
1             Good               41               Good  -5.2900 -44.4900  
2             Good               41               Good -11.2958 -41.9869  
3             Good               66           Moderate  37.1667  15.1833  
4             Good               20               Good  53.0167  20.8833

In [5]:
data2['AQI Category'].value_counts()

Good                              7708
Moderate                          7054
Unhealthy                          871
Unhealthy for Sensitive Groups     869
Very Unhealthy                     131
Hazardous                           62
Name: AQI Category, dtype: int64

In [6]:
data3 = data.copy()

In [7]:
data3['AQI Category'] = data2['AQI Category']

In [8]:
data3.head()

Country              City  AQI Value AQI Category  CO AQI Value  \
0  Russian Federation        Praskoveya         51     Moderate             1   
1              Brazil  Presidente Dutra         41         Good             1   
2              Brazil  Presidente Dutra         41         Good             1   
3               Italy   Priolo Gargallo         66     Moderate             1   
4              Poland         Przasnysz         34         Good             1   

  CO AQI Category  Ozone AQI Value Ozone AQI Category  NO2 AQI Value  \
0            Good               36               Good              0   
1            Good                5               Good              1   
2            Good                5               Good              1   
3            Good               39               Good              2   
4            Good               34               Good              0   

  NO2 AQI Category  PM2.5 AQI Value PM2.5 AQI Category      lat      lng  SO2  
0             Good               51           Moderate  44.7444  44.2031    1  
1             Good               41               Good  -5.2900 -44.4900    1  
2             Good               41               Good -11.2958 -41.9869    0  
3             Good               66           Moderate  37.1667  15.1833    1  
4             Good               20               Good  53.0167  20.8833    1

In [9]:
### Feature Engineering

#Continent

country_to_continent = {
    'Russian Federation': 'Europe',
    'Brazil': 'South America',
    'Italy': 'Europe',
    'Poland': 'Europe',
    'United States of America': 'North America',
    'Belgium': 'Europe',
    'China': 'Asia',
    'Netherlands': 'Europe',
    'France': 'Europe',
    'Colombia': 'South America',
    'Romania': 'Europe',
    'Indonesia': 'Asia',
    'Finland': 'Europe',
    'South Africa': 'Africa',
    'United Kingdom of Great Britain and Northern Ireland': 'Europe',
    'India': 'Asia',
    'Haiti': 'North America',
    'Philippines': 'Asia',
    'Latvia': 'Europe',
    'Germany': 'Europe',
    'New Zealand': 'Oceania',
    'Mexico': 'North America',
    'Japan': 'Asia',
    'El Salvador': 'North America',
    'Nigeria': 'Africa',
    'South Sudan': 'Africa',
    'Ireland': 'Europe',
    'Turkey': 'Asia',
    'Democratic Republic of the Congo': 'Africa',
    'Canada': 'North America',
    'Switzerland': 'Europe',
    'Denmark': 'Europe',
    'Cameroon': 'Africa',
    'Australia': 'Oceania',
    'Portugal': 'Europe',
    'Ethiopia': 'Africa',
    'Hungary': 'Europe',
    'Iran (Islamic Republic of)': 'Asia',
    'Israel': 'Asia',
    "Côte d'Ivoire": 'Africa',
    'Papua New Guinea': 'Oceania',
    'Madagascar': 'Africa',
    'Ghana': 'Africa',
    'Armenia': 'Asia',
    'Guatemala': 'North America',
    'Pakistan': 'Asia',
    'Thailand': 'Asia',
    'Malaysia': 'Asia',
    'Ecuador': 'South America',
    'Argentina': 'South America',
    'Peru': 'South America',
    'Dominican Republic': 'North America',
    'Azerbaijan': 'Asia',
    'Spain': 'Europe',
    'Guinea': 'Africa',
    'Bolivia (Plurinational State of)': 'South America',
    'Chile': 'South America',
    'Republic of North Macedonia': 'Europe',
    'Kazakhstan': 'Asia',
    'Serbia': 'Europe',
    'Egypt': 'Africa',
    'Czechia': 'Europe',
    'Malawi': 'Africa',
    'Sierra Leone': 'Africa',
    'Ukraine': 'Europe',
    'Benin': 'Africa',
    'Namibia': 'Africa',
    'Albania': 'Europe',
    'Guyana': 'South America',
    'Senegal': 'Africa',
    'Lesotho': 'Africa',
    'Venezuela (Bolivarian Republic of)': 'South America',
    'Bulgaria': 'Europe',
    'Somalia': 'Africa',
    'Solomon Islands': 'Oceania',
    'Paraguay': 'South America',
    'Zimbabwe': 'Africa',
    'Austria': 'Europe',
    'Croatia': 'Europe',
    'Chad': 'Africa',
    'Honduras': 'North America',
    'United Republic of Tanzania': 'Africa',
    'Cambodia': 'Asia',
    'Uganda': 'Africa',
    'Cuba': 'North America',
    'Uruguay': 'South America',
    'Republic of Moldova': 'Europe',
    'Saint Vincent and the Grenadines': 'North America',
    'Myanmar': 'Asia',
    'Angola': 'Africa',
    'Kingdom of Eswatini': 'Africa',
    'Zambia': 'Africa',
    'Morocco': 'Africa',
    'United States': 'North America',
    'Slovakia': 'Europe',
    'Sweden': 'Europe',
    'Belarus': 'Europe',
    'Norway': 'Europe',
    'Mongolia': 'Asia',
    'Malta': 'Europe',
    'Rwanda': 'Africa',
    'Botswana': 'Africa',
    'Sri Lanka': 'Asia',
    'Burundi': 'Africa',
    'Jamaica': 'North America',
    'Kenya': 'Africa',
    'Slovenia': 'Europe',
    'Mauritius': 'Africa',
    'Nicaragua': 'North America',
    'Uzbekistan': 'Asia',
    'Republic of Korea': 'Asia',
    'Burkina Faso': 'Africa',
    'Cabo Verde': 'Africa',
    'Mozambique': 'Africa',
    'Mauritania': 'Africa',
    'Guinea-Bissau': 'Africa',
    'United Arab Emirates': 'Asia',
    'Bangladesh': 'Asia',
    'Eritrea': 'Africa',
    'Barbados': 'North America',
    'Algeria': 'Africa',
    'Saudi Arabia': 'Asia',
    'Syrian Arab Republic': 'Asia',
    'United Kingdom': 'Europe',
    'Tajikistan': 'Asia',
    'Greece': 'Europe',
    'Liberia': 'Africa',
    "Lao People's Democratic Republic": 'Asia',
    'Bulgaria': 'Europe',
    'Spain': 'Europe',
    'Bhutan': 'Asia',
    'Costa Rica': 'North America',
    'Gambia': 'Africa',
    'Kyrgyzstan': 'Asia',
    'Lithuania': 'Europe',
    'Turkey': 'Asia',
    'Viet Nam': 'Asia',
    'Bosnia and Herzegovina': 'Europe',
    'Saint Lucia': 'North America',
    'Iraq': 'Asia',
    'Mali': 'Africa',
    'Sri Lanka': 'Asia',
    'Georgia': 'Asia',
    'Peru': 'South America',
    'Libya': 'Africa',
    'Niger': 'Africa',
    'Central African Republic': 'Africa',
    'Sudan': 'Africa',
    'Trinidad and Tobago': 'North America',
    'Tanzania': 'Africa',
    'Comoros Komori جزر القمر': 'Africa',
    'Turkmenistan': 'Asia',
    'Croatia': 'Europe',
    'Mozambique': 'Africa',
    'Gabon': 'Africa',
    'Estonia': 'Europe',
    'Panama': 'North America',
    'Bahrain': 'Asia',
    'Denmark': 'Europe',
    'Togo': 'Africa',
    'Congo': 'Africa',
    'Comoros': 'Africa',
    'Nepal': 'Asia',
    'Brazil': 'South America',
    'Thailand': 'Asia',
    'Jordan': 'Asia',
    'Montenegro': 'Europe',
    'Papua Niugini': 'Oceania',
    'Equatorial Guinea': 'Africa',
    'Russian Federation': 'Europe',
    'Senegal': 'Africa',
    'Luxembourg': 'Europe',
    'Aruba': 'North America',
    'Dominican Republic': 'North America',
    'Tunisia': 'Africa',
    'Éire / Ireland': 'Europe',
    'Syrian Arab Republic': 'Asia',
    'Belize': 'North America',
    'Vanuatu': 'Oceania',
    'Finland': 'Europe',
    'Netherlands': 'Europe',
    'Andorra': 'Europe',
    'Algeria': 'Africa',
    'New Zealand/Aotearoa': 'Oceania',
    'Norway': 'Europe',
    'Iceland': 'Europe',
    'Palau': 'Oceania',
    'Suriname': 'South America',
    'Singapore': 'Asia',
    'Maldives': 'Asia',
    'Bahrain': 'Asia',
    'Guinée': 'Africa',
    'Lebanon': 'Asia',
    'Seychelles': 'Africa',
    'State of Palestine': 'Asia',
    'Cyprus': 'Asia',
    'Afghanistan': 'Asia',
    'Pakistan': 'Asia',
    'Yemen': 'Asia',
    'The Bahamas': 'North America',
    'Oman': 'Asia',
    'Sāmoa': 'Oceania',
    'Kuwait': 'Asia',
    'Saint Kitts and Nevis': 'North America',
    'Qatar': 'Asia',
    'Monaco': 'Europe',
    'България': 'Europe',
    'Guiné-Bissau': 'Africa',
    '日本': 'Asia',
    'Italia': 'Europe',
    'Nederland': 'Europe',
    'Comores Komori جزر القمر': 'Africa',
    'မြန်မာ': 'Asia',
    'Norge': 'Europe',
    'Suomi / Finland': 'Europe',
    'Sénégal': 'Africa',
    'Hrvatska': 'Europe',
    'سوريا': 'Asia',
    'پاکستان': 'Asia',
    'México': 'North America',
    'República Dominicana': 'North America',
    'Sverige': 'Europe',
    'Türkiye': 'Asia',
    'Algérie': 'Africa',
    'Россия': 'Asia',
    'Moçambique': 'Africa',
    'Perú': 'South America',
    'ශ්\u200dරී ලංකාව இலங்கை': 'Asia',
    "Côte d'Ivoire": 'Africa',
    'البحرين': 'Asia',
    'Danmark': 'Europe',
    'Brasil': 'South America',
    'España': 'Europe',
    'ประเทศไทย': 'Asia'
}

# Create the 'Continent' variable using the mapping
data3['Continent'] = data3['Country'].map(country_to_continent)

data3['Continent'] = data3['Continent']

In [10]:
data3.head()

Country              City  AQI Value AQI Category  CO AQI Value  \
0  Russian Federation        Praskoveya         51     Moderate             1   
1              Brazil  Presidente Dutra         41         Good             1   
2              Brazil  Presidente Dutra         41         Good             1   
3               Italy   Priolo Gargallo         66     Moderate             1   
4              Poland         Przasnysz         34         Good             1   

  CO AQI Category  Ozone AQI Value Ozone AQI Category  NO2 AQI Value  \
0            Good               36               Good              0   
1            Good                5               Good              1   
2            Good                5               Good              1   
3            Good               39               Good              2   
4            Good               34               Good              0   

  NO2 AQI Category  PM2.5 AQI Value PM2.5 AQI Category      lat      lng  SO2  \
0             Good               51           Moderate  44.7444  44.2031    1   
1             Good               41               Good  -5.2900 -44.4900    1   
2             Good               41               Good -11.2958 -41.9869    0   
3             Good               66           Moderate  37.1667  15.1833    1   
4             Good               20               Good  53.0167  20.8833    1   

       Continent  
0         Europe  
1  South America  
2  South America  
3         Europe  
4         Europe

In [11]:
data3 = data3.drop(['AQI Value', 'CO AQI Category','Ozone AQI Category','NO2 AQI Category','PM2.5 AQI Category','lat','lng'], axis=1)

In [12]:
data3.head()

Country              City AQI Category  CO AQI Value  \
0  Russian Federation        Praskoveya     Moderate             1   
1              Brazil  Presidente Dutra         Good             1   
2              Brazil  Presidente Dutra         Good             1   
3               Italy   Priolo Gargallo     Moderate             1   
4              Poland         Przasnysz         Good             1   

   Ozone AQI Value  NO2 AQI Value  PM2.5 AQI Value  SO2      Continent  
0               36              0               51    1         Europe  
1                5              1               41    1  South America  
2                5              1               41    0  South America  
3               39              2               66    1         Europe  
4               34              0               20    1         Europe

In [ ]:
data['Country'].value_counts()

United States of America    3954
Germany                     1072
Brazil                       890
Russian Federation           889
Italy                        866
                            ... 
Andorra                        1
Algérie                        1
New Zealand/Aotearoa           1
Republic of Korea              1
Monaco                         1
Name: Country, Length: 212, dtype: int64

In [13]:
data4 = data3.copy()

In [14]:
X = data4.drop(['Country','AQI Category','City'], axis=1)
y = data4['AQI Category']

In [15]:
X

CO AQI Value  Ozone AQI Value  NO2 AQI Value  PM2.5 AQI Value  SO2  \
0                 1               36              0               51    1   
1                 1                5              1               41    1   
2                 1                5              1               41    0   
3                 1               39              2               66    1   
4                 1               34              0               20    1   
...             ...              ...            ...              ...  ...   
16690             1               34              5               54    2   
16691             1               39              1               71    2   
16692             1               39              1               71    1   
16693             1               20              5               50    1   
16694             1               44              2               71    1   

           Continent  
0             Europe  
1      South America  
2      South America  
3             Europe  
4             Europe  
...              ...  
16690  North America  
16691         Europe  
16692         Europe  
16693         Europe  
16694  North America  

[16695 rows x 6 columns]

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16695 entries, 0 to 16694
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   CO AQI Value     16695 non-null  int64 
 1   Ozone AQI Value  16695 non-null  int64 
 2   NO2 AQI Value    16695 non-null  int64 
 3   PM2.5 AQI Value  16695 non-null  int64 
 4   SO2              16695 non-null  int64 
 5   Continent        16695 non-null  object
dtypes: int64(5), object(1)
memory usage: 782.7+ KB


In [16]:
y.value_counts()

Good                              7708
Moderate                          7054
Unhealthy                          871
Unhealthy for Sensitive Groups     869
Very Unhealthy                     131
Hazardous                           62
Name: AQI Category, dtype: int64

In [17]:
y_cat = ['Good', 'Moderate', 'Unhealthy','Unhealthy for Sensitive Groups','Very Unhealthy','Hazardous']
y = pd.Categorical(y, categories=y_cat, ordered=True)

In [18]:
from sklearn.preprocessing import LabelEncoder

label_mapping = {
    'Good': 0,
    'Moderate': 1,
    'Unhealthy': 2,
    'Unhealthy for Sensitive Groups':3,
    'Very Unhealthy':4,
    'Hazardous':5
}

# Map labels to numeric values using the mapping dictionary
y= y.map(label_mapping)

In [19]:
y

[1, 0, 0, 1, 0, ..., 1, 1, 1, 0, 1]
Length: 16695
Categories (6, int64): [0 < 1 < 2 < 3 < 4 < 5]

In [20]:
y = pd.Categorical(y, ordered=True)

In [21]:
y.dtype

CategoricalDtype(categories=[0, 1, 2, 3, 4, 5], ordered=True)

In [22]:
X = pd.get_dummies(X, columns=['Continent'], drop_first=True)
X.head()

CO AQI Value  Ozone AQI Value  NO2 AQI Value  PM2.5 AQI Value  SO2  \
0             1               36              0               51    1   
1             1                5              1               41    1   
2             1                5              1               41    0   
3             1               39              2               66    1   
4             1               34              0               20    1   

   Continent_Asia  Continent_Europe  Continent_North America  \
0               0                 1                        0   
1               0                 0                        0   
2               0                 0                        0   
3               0                 1                        0   
4               0                 1                        0   

   Continent_Oceania  Continent_South America  
0                  0                        0  
1                  0                        1  
2                  0                        1  
3                  0                        0  
4                  0                        0

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
### Random Forest ###

# https://machinelearningmastery.com/random-forest-ensemble-in-python/
# https://scikit-learn.org/stable/modules/ensemble.html
# https://towardsdatascience.com/an-implementation-and-explanation-of-the-random-forest-in-python-77bf308a9b76
# https://towardsdatascience.com/improving-random-forest-in-python-part-1-893916666cd


In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, classification_report, precision_recall_curve
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, GridSearchCV, RandomizedSearchCV

In [25]:
### Function For ROC Curve
#Inputs are y_test and y_prob
#Make sure to calculate y_prob in each model before generating ROC curve

def plot_ROC(y_test, y_prob):
    from sklearn import metrics
    false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_prob)
    roc_auc = metrics.auc(false_positive_rate, true_positive_rate)
    sns.set_theme(style = 'white')
    plt.figure(figsize = (3, 3))
    plt.plot(false_positive_rate,true_positive_rate, color = '#b01717', label = 'AUC = %0.3f' % roc_auc)
    plt.legend(loc = 'lower right')
    plt.plot([0, 1], [0, 1], linestyle = '--', color = '#174ab0')
    plt.axis('tight')
    plt.ylabel('True Positive Rate')
    plt.xlabel('False Positive Rate')
    plt.show()

In [26]:
### Function For Confusion matrix

def plot_confusion_matrix(y_test, y_pred):
    acc = round(accuracy_score(y_test, y_pred), 2)
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt=".0f")
    plt.xlabel('y_pred')
    plt.ylabel('y_test')
    plt.title('Accuracy Score: {0}'.format(acc), size=10)
    plt.show(block=True)

In [27]:
rf = RandomForestClassifier(random_state = 42, max_depth = 5)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:,1]

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test,y_pred))

=== Confusion Matrix ===
[[1569    0    0    0    0    0]
 [   0 1431    0    0    0    0]
 [   0   10  147    1    0    0]
 [   0   18    3  126    0    0]
 [   0    0   25    0    0    0]
 [   0    1    7    1    0    0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1569
           1       0.98      1.00      0.99      1431
           2       0.81      0.93      0.86       158
           3       0.98      0.86      0.92       147
           4       0.00      0.00      0.00        25
           5       0.00      0.00      0.00         9

    accuracy                           0.98      3339
   macro avg       0.63      0.63      0.63      3339
weighted avg       0.97      0.98      0.98      3339



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
# Feature importance
f_imp3 = pd.DataFrame(columns = ['feature', 'importance'], index = range(10))
for i in range(len(f_imp3.index)):
    f_imp3.iloc[i, 0] = X_train.columns.to_list()[i]
f_imp3['importance'] = rf.feature_importances_
f_imp3 = f_imp3.sort_values('importance', ascending = False)
f_imp3[0:12].style.background_gradient(cmap = 'Blues')

In [29]:

from sklearn.svm import SVC

svc = SVC(random_state = 42, probability = True)
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test,y_pred))

=== Confusion Matrix ===
[[1541   28    0    0    0    0]
 [  19 1412    0    0    0    0]
 [   0    0  158    0    0    0]
 [   0    2   11  134    0    0]
 [   0    0    5    0   19    1]
 [   0    0    0    0    0    9]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      1569
           1       0.98      0.99      0.98      1431
           2       0.91      1.00      0.95       158
           3       1.00      0.91      0.95       147
           4       1.00      0.76      0.86        25
           5       0.90      1.00      0.95         9

    accuracy                           0.98      3339
   macro avg       0.96      0.94      0.95      3339
weighted avg       0.98      0.98      0.98      3339



In [31]:
from xgboost import XGBClassifier

xgb = XGBClassifier(random_state = 42, max_depth = 5, objective='multi:softmax', num_class=6)
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)
y_prob = xgb.predict_proba(X_test)[:,1]

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test,y_pred))

=== Confusion Matrix ===
[[1569    0    0    0    0    0]
 [   0 1431    0    0    0    0]
 [   0    0  158    0    0    0]
 [   0    0    0  147    0    0]
 [   0    0    0    0   25    0]
 [   0    0    0    0    0    9]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1569
           1       1.00      1.00      1.00      1431
           2       1.00      1.00      1.00       158
           3       1.00      1.00      1.00       147
           4       1.00      1.00      1.00        25
           5       1.00      1.00      1.00         9

    accuracy                           1.00      3339
   macro avg       1.00      1.00      1.00      3339
weighted avg       1.00      1.00      1.00      3339



In [32]:
y_pred = xgb.predict(X_train)
y_prob = xgb.predict_proba(X_train)[:,1]

print("=== Confusion Matrix ===")
print(confusion_matrix(y_train, y_pred))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_train,y_pred))

=== Confusion Matrix ===
[[6139    0    0    0    0    0]
 [   0 5623    0    0    0    0]
 [   0    0  713    0    0    0]
 [   0    0    0  722    0    0]
 [   0    0    0    0  106    0]
 [   0    0    0    0    0   53]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6139
           1       1.00      1.00      1.00      5623
           2       1.00      1.00      1.00       713
           3       1.00      1.00      1.00       722
           4       1.00      1.00      1.00       106
           5       1.00      1.00      1.00        53

    accuracy                           1.00     13356
   macro avg       1.00      1.00      1.00     13356
weighted avg       1.00      1.00      1.00     13356



In [33]:
# Feature importance
f_imp3 = pd.DataFrame(columns = ['feature', 'importance'], index = range(10))
for i in range(len(f_imp3.index)):
    f_imp3.iloc[i, 0] = X_train.columns.to_list()[i]
f_imp3['importance'] = xgb.feature_importances_
f_imp3 = f_imp3.sort_values('importance', ascending = False)
f_imp3[0:12].style.background_gradient(cmap = 'Blues')

In [34]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
y_prob = knn.predict_proba(X_test)[:,1]

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test,y_pred))

=== Confusion Matrix ===
[[1559   10    0    0    0    0]
 [  22 1403    0    6    0    0]
 [   0    0  157    0    1    0]
 [   0    3   10  134    0    0]
 [   0    0    4    0   20    1]
 [   0    0    0    0    0    9]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1569
           1       0.99      0.98      0.99      1431
           2       0.92      0.99      0.95       158
           3       0.96      0.91      0.93       147
           4       0.95      0.80      0.87        25
           5       0.90      1.00      0.95         9

    accuracy                           0.98      3339
   macro avg       0.95      0.95      0.95      3339
weighted avg       0.98      0.98      0.98      3339



In [36]:
from sklearn.linear_model import LogisticRegression

logistic_reg = LogisticRegression(
    multi_class='multinomial',  # Multinomial logistic regression
    solver='lbfgs',            # Optimization algorithm
    penalty='l2',              # L2 regularization (ridge penalty)
    C=1.0,                      # Inverse of regularization strength (you can adjust this)
    max_iter=1000               # Maximum number of iterations
)


logistic_reg.fit(X_train, y_train)
y_pred = logistic_reg.predict(X_test)
y_prob = logistic_reg.predict_proba(X_test)[:,1]

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test,y_pred))

=== Confusion Matrix ===
[[1482   87    0    0    0    0]
 [  79 1348    0    4    0    0]
 [   0    0  146   12    0    0]
 [   0   41   35   71    0    0]
 [   0    0   14    0    6    5]
 [   0    0    0    0    4    5]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.95      0.94      0.95      1569
           1       0.91      0.94      0.93      1431
           2       0.75      0.92      0.83       158
           3       0.82      0.48      0.61       147
           4       0.60      0.24      0.34        25
           5       0.50      0.56      0.53         9

    accuracy                           0.92      3339
   macro avg       0.75      0.68      0.70      3339
weighted avg       0.91      0.92      0.91      3339



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
